CC=gcc
CFLAGS=-Wall

altura:
	$(CC) src/$@.c -g -o bin/$@
bhaskara:
	$(CC) src/$@.c -g -o bin/$@
bytes:
	$(CC) src/$@.c -g -o bin/$@
decomposicao:
	$(CC) src/$@.c -g -o bin/$@
idade:
	$(CC) src/$@.c -g -o bin/$@
impostos:
	$(CC) src/$@.c -g -o bin/$@
media:
	$(CC) src/$@.c -g -o bin/$@
pizza:
	$(CC) src/$@.c -g -o bin/$@
tempo:
	$(CC) src/$@.c -g -o bin/$@
triangulo:
	$(CC) src/$@.c -g -o bin/$@
