CC=gcc
CFLAGS=-Wall

default: questao-1-media questao-2-triangulo questao-3-pizza questao-4-impostos questao-5-bytes questao-6-bhaskara questao-7-altura questao-8-tempo questao-9-idade questao-10-decomposicao

questao-1-media:
	$(CC) -lm src/$@.c -g -o bin/media
questao-2-triangulo:
	$(CC) -lm src/$@.c -g -o bin/triangulo
questao-3-pizza:
	$(CC) -lm src/$@.c -g -o bin/pizza
questao-4-impostos:
	$(CC) -lm src/$@.c -g -o bin/impostos
questao-5-bytes:
	$(CC) -lm src/$@.c -g -o bin/bytes
questao-6-bhaskara:
	$(CC) -lm src/$@.c -g -o bin/bhaskara
questao-7-altura:
	$(CC) -lm src/$@.c -g -o bin/altura
questao-8-tempo:
	$(CC) -lm src/$@.c -g -o bin/tempo
questao-9-idade:
	$(CC) -lm src/$@.c -g -o bin/idade
questao-10-decomposicao:
	$(CC) -lm src/$@.c -g -o bin/decomposicao
