CC = gcc
CFLAGS = -Wall -lm -g

all: 1 2 3 4 5 6 7 8 9 10
1:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
2:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
3:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
4:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
5:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
6:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
7:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
8:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
9:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
10:
	$(CC) $(CFLAGS) src/questao-$@.c -o bin/questao-$@
